#!/bin/sh /etc/rc.common
# /etc/init.d/fbis
START=95
USE_PROCD=1
STOP=10

start() {
  echo "[FBIS] Starting fbis services..."
  /usr/sbin/fbis_core &
  /usr/sbin/python3 /usr/sbin/fbisd.py &
}

start_service() {
    procd_open_instance
    procd_set_param command /usr/sbin/fbis_core -c /etc/fbis/fbis.conf
    procd_set_param respawn
    procd_close_instance

    procd_open_instance
    procd_set_param command /usr/bin/python3 /usr/sbin/fbisd.py
    procd_set_param respawn
    procd_close_instance
}


stop() {
  echo "[FBIS] Stopping fbis services..."
  killall fbis_core 2>/dev/null || true
  killall fbisd.py 2>/dev/null || true
}
stop_service() {
    procd_kill_instance
}